id: P004398
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN5138
  title: དཔལ་ནཱ་ལེནྡྲའི་ཉེར་མཁོའི་ཆོས་སྤྱོད་སྐལ་བཟང་ཐར་ལམ་བགྲོད་པའི་གཤོག་གཟུང་།༼ཚར་པའི་དཔེ་ཚོགས།༽
  author: ''
  volumes: {}
