id: P004398
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 2021-12-17 11:18:13.626865
source_metadata:
  id: bdr:W3CN5138
  title: དཔལ་ནཱ་ལེནྡྲའི་ཉེར་མཁོའི་ཆོས་སྤྱོད་སྐལ་བཟང་ཐར་ལམ་བགྲོད་པའི་གཤོག་གཟུང་།༼ཚར་པའི་དཔེ་ཚོགས།༽
  author: ''
  volumes:
    be779b233d404f8fac965ffc2d267681:
      image_group_id: I3CN5140
      title: ''
      volume_number: 1
      total_pages: 320
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
